//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFly.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class PackageInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PackageInfo()
        {
            this.BookedPackages = new HashSet<BookedPackage>();
            this.PassengerFlights = new HashSet<PassengerFlight>();
        }
    
        public string PackageID { get; set; }
        public string HotelName { get; set; }
        public string HotelImage { get; set; }
        public HttpPostedFileBase H_PhotoFile { get; set; }
        public string Destination { get; set; }
        public string PackageSubDesc { get; set; }
        public string PackageDesc { get; set; }
        public Nullable<int> PackagePrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookedPackage> BookedPackages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PassengerFlight> PassengerFlights { get; set; }
    }
}
